### ISSUE TITLE
Error in Exercise Reqs 

### ISSUE THREAD

**Issue by econometrickk** [aeturrell/coding-for-economists#36]
In the Working With Data there is an exercise 

> Create a pandas dataframe using the data=, index=, and columns= keyword arguments. The data should consist of one column with ascending integers from 0 to 5, the column name should be “series”, and the index should be the first 5 letters of the alphabet. Remember that the index and columns keyword arguments expect an iterable of some kind (not just a string).

I believe this is impossible due to there being 6 integers 0 to 5 but only 5 letters of the alphabet. 

```
import pandas as pd

data = {"Series": list(range(6))}
index = list("abcdef")
df = pd.DataFrame(data=data, index=index)

print(df)
```

I believe this satisfies the exercise requirements.

**Comment by aeturrell** [comment]
Thank you so much for flagging this error—the book can only be what it is with help from users. I hope that the referenced commit fixes the error sufficiently.
