### ISSUE TITLE
Issue on page /vis-common-plots.html

### ISSUE THREAD

**Issue by alshan** [aeturrell/coding-for-economists#40]
> You may be wondering why **Lets-Plot** isn’t featured here: its functions have almost exactly the same names as those in lets-plot, and we have opted to include the latter as it is currently the more mature plotting package.

Did you mean 
> You may be wondering why **plotnine** isn’t featured here..

?

**Comment by aeturrell** [comment]
I did, thanks so much for pointing this out!

Arthur

**Comment by aeturrell** [comment]
closed in [564f667](https://github.com/aeturrell/coding-for-economists/commit/564f6674e29dc7cc104e099a32095c4338e03f43)
