### ISSUE TITLE
Lets-Plot: geom_segment() instead of geom_path()

### ISSUE THREAD

**Issue by ASmirnov-HORIS** [aeturrell/coding-for-economists#44]
In section [Common Plots / Connected scatter plot](https://aeturrell.github.io/coding-for-economists/vis-common-plots.html#id8) you could replace the code for Lets-Plot with

```python
path_df = df.iloc[:-1].reset_index(drop=True).join(
    df.iloc[1:].reset_index(drop=True), lsuffix='_from', rsuffix='_to'
)

(
    ggplot(df, aes("Unemployment", "Vacancies"))
    + geom_segment(aes(x="Unemployment_from", y="Vacancies_from", xend="Unemployment_to", yend="Vacancies_to"), \
                 data=path_df, size=1, color="gray", arrow=arrow(type='closed', length=20, angle=15))
    + geom_point(shape=21, color="gray", fill="#c28dc3", size=5)
    + geom_text(aes(label='Year'), data=df[df['Year'].isin([2001, 2021])], position=position_nudge(y=0.3))
    + labs(x="Unemployment rate, %", y="Vacancy rate, %")
)
```

This allows to build a nicer looking plot:

![image](https://github.com/aeturrell/coding-for-economists/assets/26162403/035343e4-23fb-4ee3-afab-c90c9e1b0237)

It's already been replaced in [PR #43](https://github.com/aeturrell/coding-for-economists/pull/43), if you prefer that way of updating code.

**Comment by aeturrell** [comment]
closed in #43
