### ISSUE TITLE
Lets-Plot: joint_plot() instead of ggmarginal()

### ISSUE THREAD

**Issue by ASmirnov-HORIS** [aeturrell/coding-for-economists#45]
In section [Common Plots / Marginal histograms](https://aeturrell.github.io/coding-for-economists/vis-common-plots.html#id45) you could replace the code for Lets-Plot with

```python
from lets_plot.bistro.joint import *

(
    joint_plot(penguins, x="bill_length_mm", y="bill_depth_mm", reg_line=False)
    + labs(
        x="Bill length (mm)",
        y="Bill depth (mm)"
    )
)
```

This simplifies the code a bit and uses the function that is designed for the task at hand.

It's already been replaced in [PR #43](https://github.com/aeturrell/coding-for-economists/pull/43), if you prefer that way of updating code.

**Comment by aeturrell** [comment]
closed in #43
