### ISSUE TITLE
Lets-Plot: geom_area() instead of geom_freqpoly()

### ISSUE THREAD

**Issue by ASmirnov-HORIS** [aeturrell/coding-for-economists#46]
In section [Common Plots / Overlapping Area plot](https://aeturrell.github.io/coding-for-economists/vis-common-plots.html#id68) you could replace the code for Lets-Plot with

```python
(
    ggplot(
        planets.groupby(["year", "method"])["number"].sum().reset_index(),
        aes(x="year", y="number", fill="method", group="method", color="method"),
    )
    + geom_area(alpha=.5)
    + scale_x_continuous(format="d")
)
```

This allows to build a nicer looking plot:

![image](https://github.com/aeturrell/coding-for-economists/assets/26162403/09238c23-5a10-4efb-85a4-5a4abddbb015)

It's already been replaced in [PR #43](https://github.com/aeturrell/coding-for-economists/pull/43), if you prefer that way of updating code.

**Comment by aeturrell** [comment]
closed in #43
