### ISSUE TITLE
Lets-Plot: geom_contourf() instead of geom_contour()

### ISSUE THREAD

**Issue by ASmirnov-HORIS** [aeturrell/coding-for-economists#48]
In section [Common Plots / Contour Plot](https://aeturrell.github.io/coding-for-economists/vis-common-plots.html#id83) you could replace the code for Lets-Plot with

```python
contour_data = {'x': X.flatten(), 'y': Y.flatten(), 'z': Z.flatten()}
(
    ggplot(contour_data)
    + geom_contourf(aes(x='x', y='y', z='z', fill='..level..')) 
    + scale_fill_viridis(option="plasma")
    + ggtitle("Maths equations don't currently work")
)
```

This allows to build a nicer looking plot:

![image](https://github.com/aeturrell/coding-for-economists/assets/26162403/cdbbf1ab-950b-4c46-b2f2-5f99f90d8c7f)

It's already been replaced in [PR #43](https://github.com/aeturrell/coding-for-economists/pull/43), if you prefer that way of updating code.

**Comment by aeturrell** [comment]
closed in #43
