### ISSUE TITLE
Lets-Plot: notes for pyramid

### ISSUE THREAD

**Issue by ASmirnov-HORIS** [aeturrell/coding-for-economists#49]
In section [Common Plots / Pyramid](https://aeturrell.github.io/coding-for-economists/vis-common-plots.html#id88) there is a few issues with the plot:

- Clipped labels: unfortunately, the 20 character limit is hardcoded, so y labels are cut off. But the full text can be seen in the axial tooltip.

- Weird-looking tooltips on top of the pyramid: to improve tooltips displaying I suggest not to use identity statistic; you can calculate and add weight for users as shown below:

  ```python
  g = (
      ggplot(df, aes(x="Stage", y="Users", fill="Gender", weight='Users'))
      + geom_bar(width=0.8)  # baseplot
      + coord_flip()  # flip coordinates
      + theme_minimal()
      + ylab("Users (millions)")
  )
  g
  ```

  It's already been replaced in [PR #43](https://github.com/aeturrell/coding-for-economists/pull/43), if you prefer that way of updating code.

**Comment by aeturrell** [comment]
closed in #43
