### ISSUE TITLE
Lets-Plot: add Lets-Plot to geo-spatial visualisation

### ISSUE THREAD

**Issue by ASmirnov-HORIS** [aeturrell/coding-for-economists#50]
The Lets-Plot library is not mentioned in the [Geo-Spatial Visualization](https://aeturrell.github.io/coding-for-economists/geo-vis.html) section. However, it can work with cartographic data. Detailed information about geocoding can be found [here](https://lets-plot.org/pages/geocoding.html).

Basic example with UK districts:

```python
from lets_plot.geo_data import *

country = geocode_counties().scope('UK').inc_res().get_boundaries()

ggplot() + geom_map(data=country, show_legend=False, size=0.2)
```

![image](https://github.com/aeturrell/coding-for-economists/assets/26162403/e5345c1b-7275-4b2d-b06b-b3dca0d57891)

Also, you can add an interactive basemap layer to create a beautiful map:

```python
(
    ggplot() 
    + geom_livemap() 
    + geom_map(aes(fill='found name'), data=country, show_legend=False, size=0.2) 
)
```

![image](https://github.com/aeturrell/coding-for-economists/assets/26162403/1642c844-3feb-4027-9fbb-bbdfb44f6c94)

**Comment by aeturrell** [comment]
Fixed in [5a13688](https://github.com/aeturrell/coding-for-economists/commit/5a13688d922193f936512bccfa2a4342368ff8f4)
