### ISSUE TITLE
No R2 values reported with `pyfixest` in chapter 6

### ISSUE THREAD

**Issue by s3alfisc** [aeturrell/coding-for-economists#58]
Hi @aeturrell, the `pyfixest` version which you ran the coding for economists regression chapter with did not report R2 values but only the RMSE. If you upgrade to pyfixest `0.14.0`, this should be fixed =) 
Best, Alex
![image](https://github.com/aeturrell/coding-for-economists/assets/19531450/81ea21aa-a278-4550-be14-765e42710dc6)

**Comment by aeturrell** [comment]
Thanks for the spot Alex, will do!

**Comment by aeturrell** [comment]
Hey @s3alfisc this triggered a couple of issues, will flag them on the repo

**Comment by aeturrell** [comment]
Closed in 1e28074
