### ISSUE TITLE
Non-breaking API changes for `pyfixest` version `0.17.0`

### ISSUE THREAD

**Issue by s3alfisc** [aeturrell/coding-for-economists#70]
Hi @aeturrell , please see my comment in the associated PR: https://github.com/aeturrell/coding-for-economists/pull/69. 
Best, Alex

**Comment by s3alfisc** [comment]
Just released pyfixest `0.17.0` . You can find the full changelog [here](https://s3alfisc.github.io/pyfixest/news.html#pyfixest-0.17.0) =)

**Comment by aeturrell** [comment]
#69 merged!
