### ISSUE TITLE
Small typo

### ISSUE THREAD

**Issue by dvmasterov** [aeturrell/coding-for-economists#75]
In [column-and-row-exercises](https://aeturrell.github.io/coding-for-economists/data-intro.html#column-and-row-exercises), there is a missing question mark:

> 1.  Compare `air_time` with `arr_time - dep_time`. What do you expect to see? What do you see**?** What do you need to do to fix it?\n",

**Comment by aeturrell** [comment]
Many thanks for flagging this @dvmasterov!

**Comment by aeturrell** [comment]
Fixed in d0e9ba2
